# Generated by Django 2.0 on 2018-09-15 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Memes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(verbose_name='link')),
                ('thumbnail_small', models.URLField(verbose_name='thumbnail_small')),
                ('thumbnail_small_square', models.URLField(verbose_name='thumbnail_small_square')),
                ('thumbnail_huge', models.URLField(verbose_name='thumbnail_huge')),
                ('thumbnail_big_square', models.URLField(verbose_name='thumbnail_big_square')),
                ('transcribe', models.TextField()),
                ('likes', models.IntegerField()),
            ],
        ),
    ]
