# Generated by Django 2.0 on 2018-09-15 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='memes',
            name='likes',
            field=models.IntegerField(default=0),
        ),
    ]
