# Generated by Django 2.0 on 2018-09-15 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('memes', '0002_auto_20180915_1015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memes',
            name='thumbnail_big_square',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='thumbnail_huge',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='thumbnail_small',
        ),
        migrations.RemoveField(
            model_name='memes',
            name='thumbnail_small_square',
        ),
        migrations.AddField(
            model_name='memes',
            name='thumbnail',
            field=models.URLField(default='no_link', verbose_name='thumbnail'),
            preserve_default=False,
        ),
    ]
